# Simularium Conversion Tutorial : Custom Data

In [1]:
from IPython.display import Image
import numpy as np
from simulariumio import Converter

This notebook provides example python code for converting your own simulation trajectories into the format consumed by the Simularium Viewer. It creates a .simularium JSON file which you can drag and drop onto the viewer like this:

![title](img/drag_drop.gif)

***
## Prepare your spatial data

The Simularium custom data Converter consumes spatiotemporal data from any source. It requires the following data:
* **box_size** : *np.ndarray (shape = [3])*
    * A numpy ndarray containing the XYZ dimensions of the simulation bounding volume
* **times** : *np.ndarray (shape = [timesteps])*
    * A numpy ndarray containing the elapsed simulated time at each timestep
* **n_agents** : *np.ndarray (shape = [timesteps])*
    * A numpy ndarray containing the number of agents that exist at each timestep
* **viz_types** : *np.ndarray (shape = [timesteps, agents])*
    * A numpy ndarray containing the viz type for each agent at each timestep. Current options:
        * 1000 : default,
        * 1001 : fiber (which will require subpoints)
* **positions** : *np.ndarray (shape = [timesteps, agents, 3])*
    * A numpy ndarray containing the XYZ position for each agent at each timestep
* **types** : *List[List[str]] (list of shape [timesteps, agents])*
    * A list containing timesteps, for each a list of the string name for the type of each agent
* **radii** : *np.ndarray (shape = [timesteps, agents])*
    * A numpy ndarray containing the radius for each agent at each timestep
    
Optionally, you can also include:
* **n_subpoints** : *np.ndarray (shape = [timesteps, agents]) (optional)*
    * A numpy ndarray containing the number of subpoints belonging to each agent at each timestep. Required if subpoints are provided
* **subpoints** : *np.ndarray (shape = [timesteps, agents, subpoints, 3])*
    * A numpy ndarray containing a list of subpoint position data for each agent at each timestep. These values are currently only used for fiber agents.
* **plots** : *Dict[str, Any]*
    * An object containing plot data already in Simularium format

### Generate example data

To demonstrate using the custom converter, we'll first generate some random example data.

In [2]:
from string import ascii_uppercase
from random import choice

# parameters
total_steps = 5
timestep = 0.5
box_size = 100
n_agents = 5
min_radius = 5
max_radius = 10
agents_are_fibers = True
points_per_fiber = 4

example_data = {
    "box_size" : np.array([box_size, box_size, box_size]),
    "times" : timestep * np.array(list(range(total_steps))),
    "n_agents" : np.array(total_steps * [n_agents]),
    "types" : []
}
for t in range(total_steps):
    example_data["types"].append([choice(ascii_uppercase) for i in range(n_agents)])

### Sphere visualization

If the agents are particles to be visualized as spheres, their centroid positions can be added like this:

In [3]:
if not agents_are_fibers:
    example_data["positions"] = np.random.uniform(size=(total_steps, n_agents, 3)) * box_size - box_size * 0.5
    example_data["viz_types"] = np.array(total_steps * [n_agents * [1000.0]]) # default viz type = 1000
    example_data["radii"] = (max_radius - min_radius) * np.random.uniform(size=(total_steps, n_agents)) + min_radius

### Line visualization

If the agents are fibers to be visualized as lines, the positions of points along each fiber can be added using the optional subpoints:

In [4]:
if agents_are_fibers:
    example_data["positions"] = np.zeros(shape=(total_steps, n_agents, 3))
    example_data["n_subpoints"] = points_per_fiber * np.ones(shape=(total_steps, n_agents))
    example_data["subpoints"] = box_size * np.random.uniform(
        size=(total_steps, n_agents, points_per_fiber, 3)) - box_size * 0.5
    example_data["viz_types"] = np.array(total_steps * [n_agents * [1001.0]]) # fiber viz type = 1001
    example_data["radii"] = np.zeros(shape=(total_steps, n_agents))

Inspect the resulting data:

In [6]:
print("box size = {}".format(example_data["box_size"]))
print("times = {}".format(example_data["times"]))
print("number of agents = {}".format(example_data["n_agents"]))
print("viz types = {}".format(example_data["viz_types"]))
print("positions = {}".format(example_data["positions"]))
print("types = {}".format(example_data["types"]))
print("radii = {}".format(example_data["radii"]))
if agents_are_fibers:
    print("n_subpoints = {}".format(example_data["n_subpoints"]))
    print("subpoints = {}".format(example_data["subpoints"]))

box size = [100 100 100]
times = [0.  0.5 1.  1.5 2. ]
number of agents = [5 5 5 5 5]
viz types = [[1001. 1001. 1001. 1001. 1001.]
 [1001. 1001. 1001. 1001. 1001.]
 [1001. 1001. 1001. 1001. 1001.]
 [1001. 1001. 1001. 1001. 1001.]
 [1001. 1001. 1001. 1001. 1001.]]
positions = [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
types = [['J', 'K', 'Q', 'W', 'O'], ['F', 'B', 'P', 'E', 'D'], ['V', 'B', 'C', 'U', 'G'], ['L', 'Y', 'J', 'X', 'Q'], ['L', 'N', 'U', 'D', 'V']]
radii = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
n_subpoints = [[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
subpoints = [[[[ 13.23894823  -3.91882179

## Convert and save as .simularium JSON file

Once your data is shaped like in the `example_data` object, you can use the converter to generate the file at the given path:

In [7]:
converter = Converter(example_data)
converter.write_JSON("/Users/blairl/Desktop/example")

***
## Add plots

You can optionally include metrics data, which will be graphed in plots alongside your spatial data in the Simularium viewer. For now, Simularium supports scatterplots and histograms.

### Scatterplots

Scatterplots require the following data:
* **title** : *str*
    * A string display title for the plot
* **xaxis_title** : *str*
    * A string label (with units) for the x-axis
* **yaxis_title** : *str*
    * A string label (with units) for the y-axis
* **xtrace** : *np.ndarray (shape = [x values])*
    * A numpy ndarray of values for x, the independent variable
* **ytraces** : *Dict[str, np.ndarray (shape = [x values])]*
    * A dictionary with y-trace display names as keys, each mapped to a numpy ndarray of values for y, the dependent variable
* **render_mode** : *str (optional)*
    * A string specifying how to draw the datapoints. Options:
        * 'markers' : draw as points
        * 'lines' : connect points with line
    * Default: 'markers'

Here's some random example scatterplot data:

In [8]:
scatter_plot = {
    "title": "Test Scatterplot 1",
    "xaxis_title": "time (ns)",
    "yaxis_title": "concentration (uM)",
    "xtrace": np.array(list(range(10))),
    "ytraces": {
        "agent1": 100 * np.random.uniform(size=(10)),
        "agent2": 100 * np.random.uniform(size=(10)),
        "agent3": 100 * np.random.uniform(size=(10)),
    },
    "render_mode": "lines"
}

In [9]:
print("title = {}".format(scatter_plot["title"]))
print("xaxis_title = {}".format(scatter_plot["xaxis_title"]))
print("yaxis_title = {}".format(scatter_plot["yaxis_title"]))
print("xtrace = {}".format(scatter_plot["xtrace"]))
print("ytraces:")
print("  agent1 = {}".format(scatter_plot["ytraces"]["agent1"]))
print("  agent2 = {}".format(scatter_plot["ytraces"]["agent2"]))
print("  agent2 = {}".format(scatter_plot["ytraces"]["agent3"]))
print("render_mode = {}".format(scatter_plot["render_mode"]))

title = Test Scatterplot 1
xaxis_title = time (ns)
yaxis_title = concentration (uM)
xtrace = [0 1 2 3 4 5 6 7 8 9]
ytraces:
  agent1 = [97.74796118 88.80869688 16.85452287 87.09428984 70.36843988 52.13389736
 56.33000164 90.51117137 17.02626777 25.59499449]
  agent2 = [ 9.77939458 73.4149312  64.7861666  79.75274145 17.60309876 90.88628688
 51.1341755  54.99764073 87.16545486 79.32302919]
  agent2 = [18.55540136  4.90188074 38.79896887 39.45781166  8.1098909  78.96504652
 41.45016024 82.49835386 35.60752763 25.33445869]
render_mode = lines


To add it to the converter:

In [10]:
converter.add_plot(scatter_plot, "scatter")

### Histograms

Histograms require the following data:
* **title** : *str*
    * A string display title for the plot
* ***xaxis_title*** : *str*
    * A string label (with units) for the x-axis
* **traces** : *Dict[str, np.ndarray (shape = [values])]*
    * A dictionary with trace display names as keys, each mapped to a numpy ndarray of values

Here's some random example histogram data:

In [11]:
histogram = {
    "title": "Test Histogram 1",
    "xaxis_title": "angle (degrees)",
    "traces": {
        "crosslinked monomers": 2 * np.random.uniform(size=(15)),
        "bent monomers": 10 * np.random.uniform(size=(10)),
    }
}

In [12]:
print("title = {}".format(histogram["title"]))
print("xaxis_title = {}".format(histogram["xaxis_title"]))
print("traces:")
print("  crosslinked monomers = {}".format(histogram["traces"]["crosslinked monomers"]))
print("  bent monomers = {}".format(histogram["traces"]["bent monomers"]))

title = Test Histogram 1
xaxis_title = angle (degrees)
traces:
  crosslinked monomers = [0.64069672 1.06785856 1.08027018 0.82602275 0.16817762 0.15148913
 1.6432542  1.09574196 1.62613419 1.22609412 1.65877947 0.45815282
 1.3457433  1.75896675 1.46479959]
  bent monomers = [8.74788534 9.12620809 8.639198   4.74547478 7.6194605  4.34426255
 1.44001652 8.99719582 1.04405378 4.65062688]


To add it to the converter:

In [13]:
converter.add_plot(histogram, "histogram")

### Save the data with added plots

Once you've added your plot data, write the updated data to file:

In [14]:
converter.write_JSON("/Users/blairl/Desktop/example")

## Visualize in the Simularium viewer

In your browser, either Firefox or Chrome, navigate to https://staging.agentviz.allencell.org/ and drag your file onto the center viewer window. 

*For now you'll first have to choose an example trajectory and close the load window. Once the example trajectory loads, you can drop your own file in to replace it. We'll fix this soon :)*