# Simularium Conversion Tutorial

This notebook provides example python code for converting your own simulation trajectories into the format consumed by the Simularium Viewer (https://staging.agentviz.allencell.org/)

In [1]:
import numpy as np
from simulariumio import Converter

## Generate example data

In [2]:
from string import ascii_uppercase
from random import choice

# parameters
total_steps = 5
timestep = 0.5
box_size = 100
n_agents = 5
min_radius = 5
max_radius = 10

example_data = {
    "box_size" : np.array([box_size, box_size, box_size]),
    "times" : timestep * np.array(list(range(total_steps))),
    "n_agents" : np.array(total_steps * [n_agents]),
    "viz_types" : np.array(total_steps * [n_agents * [1000.0]]),
    "positions" : np.random.uniform(size=(total_steps, n_agents, 3)) * box_size - box_size * 0.5,
    "types" : [],
    "radii" : (max_radius - min_radius) * np.random.uniform(size=(total_steps,n_agents)) + min_radius
}
for t in range(total_steps):
    example_data["types"].append([choice(ascii_uppercase) for i in range(n_agents)])


In [3]:
print("box size = {}".format(example_data["box_size"]))
print("times = {}".format(example_data["times"]))
print("number of agents = {}".format(example_data["n_agents"]))
print("viz types = {}".format(example_data["viz_types"]))
print("positions = {}".format(example_data["positions"]))
print("types = {}".format(example_data["types"]))
print("radii = {}".format(example_data["radii"]))

box size = [100 100 100]
times = [0.  0.5 1.  1.5 2. ]
number of agents = [5 5 5 5 5]
viz types = [[1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]]
positions = [[[ 20.88145807  43.37566522 -25.41375132]
  [ 37.28198722  17.88395263  23.69162917]
  [-11.81778257  -2.08572656  37.24376816]
  [-12.33927997  23.85685562   2.6290496 ]
  [ -5.1274867   29.79609104   8.15321078]]

 [[-13.55754633  29.24926512  10.06625781]
  [-12.79199318  26.03032342 -44.47159701]
  [ 41.91212083  18.23721182  14.64139992]
  [ 32.71056715 -27.12707384 -27.51635038]
  [ 44.74853446  40.55004084  41.40736453]]

 [[-34.66536562 -16.25371831 -28.6696427 ]
  [-20.42338594 -46.50046624  -8.28226239]
  [ 49.94866986  -7.343584    19.73723106]
  [-31.1784164  -38.35268048  18.58564116]
  [-41.3685786   -9.36462872 -17.8879507 ]]

 [[ 44.35913738 -49.45454853 -21.41883737]
  [-11.32136775 -43.58995664  

In [4]:
output_path = "/Users/blairl/Documents/example"

converter = Converter(example_data)
converter.write_JSON(output_path)