# Simularium Conversion Tutorial

This notebook provides example python code for converting your own simulation trajectories into the format consumed by the Simularium Viewer (https://staging.agentviz.allencell.org/)

In [1]:
import numpy as np
from simulariumio import Converter

## Generate example data

In [2]:
from string import ascii_uppercase
from random import choice

# parameters
total_steps = 5
timestep = 0.5
box_size = 100
n_agents = 5
min_radius = 5
max_radius = 10

example_data = {
    "box_size" : np.array([box_size, box_size, box_size]),
    "times" : timestep * np.array(list(range(total_steps))),
    "n_agents" : np.array(total_steps * [n_agents]),
    "viz_types" : np.array(total_steps * [n_agents * [1000.0]]),
    "positions" : np.random.uniform(size=(total_steps, n_agents, 3)) * box_size - box_size * 0.5,
    "types" : [],
    "radii" : (max_radius - min_radius) * np.random.uniform(size=(total_steps,n_agents)) + min_radius
}
for t in range(total_steps):
    example_data["types"].append([choice(ascii_uppercase) for i in range(n_agents)])


In [3]:
print("box size = {}".format(example_data["box_size"]))
print("times = {}".format(example_data["times"]))
print("number of agents = {}".format(example_data["n_agents"]))
print("viz types = {}".format(example_data["viz_types"]))
print("positions = {}".format(example_data["positions"]))
print("types = {}".format(example_data["types"]))
print("radii = {}".format(example_data["radii"]))

box size = [100 100 100]
times = [0.  0.5 1.  1.5 2. ]
number of agents = [5 5 5 5 5]
viz types = [[1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]
 [1000. 1000. 1000. 1000. 1000.]]
positions = [[[ 21.58668002 -13.70903387 -40.01734271]
  [  8.44645366  22.48904971 -43.573566  ]
  [ -4.75601564 -35.45672754 -43.80806989]
  [ 39.22006209 -24.87459765 -15.93487464]
  [ 18.93234941  -6.01700408 -37.1400693 ]]

 [[ 36.83242954 -47.4406402   -0.31906396]
  [ 39.41594664 -35.99276964 -16.03155596]
  [ 44.13765847  -6.55618312 -21.83537292]
  [ 40.06009101  46.64898841  32.51670044]
  [ 18.35847771   2.27332361   1.62294118]]

 [[ 31.86514644 -19.53448941 -26.7556161 ]
  [ -1.85528393  49.98773058   9.15825141]
  [-35.82818656 -39.52469042  -4.83443444]
  [-32.73436234   8.57162939  25.59408861]
  [-47.03069629  14.20233162  47.93431854]]

 [[ 31.77658847   7.9515801   31.35214979]
  [-29.53048539  17.65506799  

In [4]:
output_path = "/Users/blairl/Documents/example"

Converter(example_data).write_JSON(output_path)